# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "discount-test"
client_id = "654ae2cc32978a11ce8099a1a7f54376"
application_url = "https://outdoor-pictures-whats-session.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts,read_shipping,write_payment_customizations,write_discounts,read_customers,write_customers,read_discounts,unauthenticated_read_customers,customer_read_markets,customer_read_draft_orders,customer_read_orders"

[auth]
redirect_urls = [
  "https://outdoor-pictures-whats-session.trycloudflare.com/auth/callback",
  "https://outdoor-pictures-whats-session.trycloudflare.com/auth/shopify/callback",
  "https://outdoor-pictures-whats-session.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "platinummstores.myshopify.com"
